name: Data Science Stories
description: Amherst College Fall 2020
featimg: protect_the_herd.jpg

url: https://stat231-f20.github.io
baseurl: '/pug-blogs'
port: 4343
permalink: /:title/

media_folder: /media
destination: jekyllbuild
full_rebuild: true
gems: [jekyll-paginate]
paginate: 16
paginate_path: /page/:num/
infinite_scroll: true #false for pagination

tumblr: "#"
pinterest: "#"
instagram: "#"
twitter: "#"
facebook: "#"
youtube: "#"
vimeo: "#"
soundcloud: "#"

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page-full"
      type: "standard"
      homedisplay: "featimg"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-full"
      type: "standard"
      homedisplay: "featimg"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md, jekyllbuild]
